[package]
name = "rust-asm"
description = "ObjectWeb ASM implementation in Rust"
repository = "https://github.com/cubewhy/rust-asm"
documentation = "https://docs.rs/rust-asm"
version = "0.1.3"
edition = "2024"
license = "MIT"

[features]
macros = []

[dependencies]
thiserror = "2"
